### ISSUE TITLE
Fix: Lint is not working properly in CoroutineTemplate's CI

### ISSUE THREAD

**Issue by luongvo** [nimblehq/android-templates#182] opened 2022-04-06 20:07 UTC
## Issue

In `review_pull_request.yml` workflow:

<details>
  <summary>Lint is throwing some Gradle's exceptions</summary>
  
  ```
Run ./gradlew lint
  ./gradlew lint
  shell: /usr/bin/bash -e {0}
  env:
    JAVA_HOME_8.0.3[2](https://github.com/nimblehq/android-templates/runs/5856390087?check_suite_focus=true#step:8:2)2_x64: /opt/hostedtoolcache/jdk/8.0.[3](https://github.com/nimblehq/android-templates/runs/5856390087?check_suite_focus=true#step:8:3)22/x6[4](https://github.com/nimblehq/android-templates/runs/5856390087?check_suite_focus=true#step:8:4)
    JAVA_HOME: /opt/hostedtoolcache/jdk/8.0.322/x64
    JAVA_HOME_8_0_322_X64: /opt/hostedtoolcache/jdk/8.0.322/x64
> Task :buildSrc:compileKotlin UP-TO-DATE
> Task :buildSrc:compileJava NO-SOURCE
> Task :buildSrc:compileGroovy NO-SOURCE
> Task :buildSrc:pluginDescriptors UP-TO-DATE
> Task :buildSrc:processResources NO-SOURCE
> Task :buildSrc:classes UP-TO-DATE
> Task :buildSrc:inspectClassesForKotlinIC UP-TO-DATE
> Task :buildSrc:jar UP-TO-DATE
> Task :buildSrc:assemble UP-TO-DATE
> Task :buildSrc:compileTestKotlin NO-SOURCE
> Task :buildSrc:pluginUnderTestMetadata UP-TO-DATE
> Task :buildSrc:compileTestJava NO-SOURCE
> Task :buildSrc:compileTestGroovy NO-SOURCE
> Task :buildSrc:processTestResources NO-SOURCE
> Task :buildSrc:testClasses UP-TO-DATE
> Task :buildSrc:test NO-SOURCE
> Task :buildSrc:validatePlugins UP-TO-DATE
> Task :buildSrc:check UP-TO-DATE
> Task :buildSrc:build UP-TO-DATE
> Task :domain:compileKotlin
> Task :domain:compileJava NO-SOURCE
> Task :domain:processResources NO-SOURCE
> Task :domain:classes UP-TO-DATE
> Task :domain:inspectClassesForKotlinIC
> Task :domain:jar
> Task :app:preBuild UP-TO-DATE
> Task :app:preProductionDebugBuild UP-TO-DATE
> Task :data:preBuild UP-TO-DATE
> Task :data:preDebugBuild UP-TO-DATE
> Task :data:compileDebugAidl NO-SOURCE
> Task :app:compileProductionDebugAidl NO-SOURCE
> Task :data:packageDebugRenderscript NO-SOURCE
> Task :app:compileProductionDebugRenderscript NO-SOURCE
> Task :app:dataBindingMergeDependencyArtifactsProductionDebug
> Task :app:dataBindingMergeGenClassesProductionDebug
> Task :app:generateProductionDebugResValues
> Task :app:generateProductionDebugResources
> Task :data:compileDebugRenderscript NO-SOURCE
> Task :data:generateDebugResValues
> Task :data:generateDebugResources
> Task :data:packageDebugResources
> Task :app:generateProductionDebugBuildConfig
> Task :app:writeProductionDebugApplicationId
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:200)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:19[5](https://github.com/nimblehq/android-templates/runs/5856390087?check_suite_focus=true#step:8:5))
	at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:75)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:[6](https://github.com/nimblehq/android-templates/runs/5856390087?check_suite_focus=true#step:8:6)8)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:153)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:68)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:62)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.lambda$call$2(DefaultBuildOperationExecutor.java:[7](https://github.com/nimblehq/android-templates/runs/5856390087?check_suite_focus=true#step:8:7)6)
	at org.gradle.internal.operations.UnmanagedBuildOperationWrapper.callWithUnmanagedSupport(UnmanagedBuildOperationWrapper.java:54)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:76)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
	at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:41)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:372)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:35[9](https://github.com/nimblehq/android-templates/runs/5856390087?check_suite_focus=true#step:8:9))
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:352)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:338)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.lambda$run$0(DefaultPlanExecutor.java:127)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:191)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:182)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:124)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.ClassNotFoundException: com.android.tools.lint.client.api.Vendor
	at com.intellij.util.lang.UrlClassLoader.findClass(UrlClassLoader.java:357)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	... 132 more
Ran lint on variant stagingRelease: 3 issues found
Ran lint on variant productionRelease: 2 issues found
Ran lint on variant stagingDebug: 3 issues found
Ran lint on variant productionDebug: 3 issues found
Wrote HTML report to file:///home/runner/work/android-templates/android-templates/CoroutineTemplate/app/build/reports/lint-results.html
Wrote XML report to file:///home/runner/work/android-templates/android-templates/CoroutineTemplate/app/build/reports/lint/lint-result.xml

BUILD SUCCESSFUL in 2m 31s
1[10](https://github.com/nimblehq/android-templates/runs/5856390087?check_suite_focus=true#step:8:10) actionable tasks: [11](https://github.com/nimblehq/android-templates/runs/5856390087?check_suite_focus=true#step:8:11)0 executed
  ```
</details>

## Expected

- Lint should run properly and correctly in CI.

## Steps to reproduce

Check the logs at https://github.com/nimblehq/android-templates/runs/5856390087?check_suite_focus=true

**Comment by Tuubz** [comment] 2022-04-07 02:37
Possible duplicate of #168 

If it's the same should we change this issue to only fix Lint?

**Comment by luongvo** [comment] 2022-04-07 02:55
@Tuubz indeed, let me update this issue content 👌

**Comment by luongvo** [comment] 2022-04-07 02:58
@Tuubz updated, I moved `Detekt is reporting `NO-SOURCE` error` content into #168

**Comment by Tuubz** [comment] 2022-12-06 03:41
The error has disappeared after upgrading Gradle (#163)

Example: https://github.com/nimblehq/android-templates/actions/runs/3588983678/jobs/6040941397

cc @luongvo

**Closed by Tuubz** 2022-12-06 03:41 UTC
Labels: type : bug, status : essential, priority : low
