### ISSUE TITLE
Clean Files and folders after setup

### ISSUE THREAD

**Issue by suho** [nimblehq/android-templates#283] opened 2022-08-23 03:34 UTC
## Issue

After running the setup scripts, files and folders are not cleaned. As a result, I don't know which folder uses for the project.

For example, I run `kscript new_project.kts package-name=co.nimblehq.suvkmmsurveys.android app-name=Surveys`. `Surveys` or `template` is the right folder? 🤔

<img width="489" alt="Screen Shot 2022-08-23 at 10 32 57" src="https://user-images.githubusercontent.com/19943832/186063648-076b32e0-37b5-4395-a557-7e255cf9cd2e.png">

## Expected

The scripts should clean all files and folders that are not needed for the project.

## Steps to reproduce

1. Run the setup script
2. Check the folder after the project is generated

**Comment by sleepylee** [comment] 2022-08-23 03:38
I think we could rather turn this into a feature flag, because maybe you will want to continue using this template for another project without checking out the repo again right? Perhaps an option to the original command `-d` == `delete the template after finished` could be done, but not a bug

**Comment by sleepylee** [comment] 2022-08-23 03:39
or also, a path to specify where to place the templated project dir 💭

**Comment by ryan-conway** [comment] 2022-08-23 04:33
@suho I'm gonna agree with @sleepylee, this sounds like a feature rather than a bug. How about we open a [new discussion](https://github.com/nimblehq/android-templates/discussions) and let the team vote there? 😄

**Comment by sleepylee** [comment] 2022-08-23 04:35
@ryan-conway you can make the call 🙆‍♂️ just make sure that the answer pleased @suho first

**Comment by suho** [comment] 2022-08-23 04:40
@sleepylee @ryan-conway All good from my side :D. Please help me to change the label. I can't change it :D

**Comment by ryan-conway** [comment] 2023-07-06 04:09
Resolved by #436

**Closed by ryan-conway** 2023-07-06 04:09 UTC
Labels: type : feature, status : need voting, priority : normal
